clusterName: CLUSTER_1
streams:
    - name: beats
      destinations:
      - BEATS-STREAM
      filters:
        - sourceTopic: beats
          destinationStreamNames:
            - AUDITBEAT-STREAM
          keywords:
            - auditbeat
        - sourceTopic: beats
          destinationStreamNames:
            - METRICBEAT-STREAM
          keywords:
            - metricbeat
